### ISSUE TITLE
Duktape does not support DataView.getBigUint64()

### ISSUE THREAD

**Issue by qftgtr** [xxuejie/moleculec-es#3]
It seems duktape doesn't have the capability to handle BigInt and uint64, as shown [here](https://github.com/svaarala/duktape/issues/2048) and [here](https://github.com/svaarala/duktape/issues/1471). As a result, it doesn't have methods like `DataView.getBigUint64()` and `DataView.setBigUint64()` as shown [here](https://github.com/svaarala/duktape/blob/26f00693780c976b4e490af68c022bccba9d80c0/doc/buffers.rst#summary-of-read-methods).

Therefore, the use of `toBigEndianBigUint64` and `toLittleEndianBigUint64` will raise error.

https://github.com/xxuejie/moleculec-es/blob/2158f10c3d32bfd12c4bf20143bea6a81d6f9ac2/pkg/generator/generator.go#L178

**Comment by b1uesky** [comment]
Change the implementations of `toBigEndianBigUint64` and `toLittleEndianBigUint64` to something like this. They should return the expected value.
```
toBigEndianBigUint64() {
    const l = this.view.getUint32(0, false);
    const r = this.view.getUint32(4, false);
    // 1 << 32 = 4294967296
    return l * 4294967296 + r;
}

toLittleEndianBigUint64() {
    const l = this.view.getUint32(0, true);
    const r = this.view.getUint32(4, true);
    // 1 << 32 = 4294967296
    return r * 4294967296 + l;
}
```

**Comment by qftgtr** [comment]
> Change the implementations of `toBigEndianBigUint64` and `toLittleEndianBigUint64` to something like this. They should return the expected value.
> 
> ```
> toBigEndianBigUint64() {
>     const l = this.view.getUint32(0, false);
>     const r = this.view.getUint32(4, false);
>     // 1 << 32 = 4294967296
>     return l * 4294967296 + r;
> }
> 
> toLittleEndianBigUint64() {
>     const l = this.view.getUint32(0, true);
>     const r = this.view.getUint32(4, true);
>     // 1 << 32 = 4294967296
>     return r * 4294967296 + l;
> }
> ```

It may lose precision since a regular js Number cannot handle 64bit integer.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

**Comment by b1uesky** [comment]
> > Change the implementations of `toBigEndianBigUint64` and `toLittleEndianBigUint64` to something like this. They should return the expected value.
> > ```
> > toBigEndianBigUint64() {
> >     const l = this.view.getUint32(0, false);
> >     const r = this.view.getUint32(4, false);
> >     // 1 << 32 = 4294967296
> >     return l * 4294967296 + r;
> > }
> > 
> > toLittleEndianBigUint64() {
> >     const l = this.view.getUint32(0, true);
> >     const r = this.view.getUint32(4, true);
> >     // 1 << 32 = 4294967296
> >     return r * 4294967296 + l;
> > }
> > ```
> 
> It may lose precision since a regular js Number cannot handle 64bit integer.
> 
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

I see. That means, as long as the cell capacity is less than 90,071,992 CKB, this implementation would get the correct capacity :) It's probably ok for many use cases.

But I got your point, and really look forward to the solution.

**Comment by xxuejie** [comment]
I've added an option to disable those 2 functions in the generated code. The bigger problem here is that BigInt is not available in duktape. If someone wants to ship their own BigInt implementation, it should not be hard for them to add the above 2 functions themselves.
